version: '3'
services:
  jenkins:
    container_name: jekinsCurso
    image: jenkins/jenkins
    ports:
      - "8089:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    networks:
      - net
networks:
  net:
