version: '3'
services:
  remote_host:
    build: .
    image: ubuntu
    container_name: ubuntussh 
    ports:
      - "8000:22"
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sh /root/entrypoint.sh