version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    ports:
      - "8000:22"
    command: service ssh start
    command: service ssh status
    entrypoint:  tail -f /dev/null