version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    ports:
      - "8000:22"
    privileged: true
    entrypoint: tail -f /dev/null
    command: /etc/init.d/ssh start
    command: service ssh start