version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    ports:
      - "8000:22"
    privileged: true
    command: /usr/sbin/ssh -D
    entrypoint: tail -f /dev/null