version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    ports:
      - "8000:22"
    privileged: true
    entrypoint: chmod 777 /var/run/docker.sock && tail -f /dev/null
