version: '3'
services:
  remote_host:
    container_name: remote-host
    image: remote-host
    build: .
    ports:
      - "8000:22"
    privileged: true
    #command: /usr/sbin/sshd -D
    entrypoint:  /etc/init.d/sshd start && /bin/bash && tail -f /dev/null