version: "3.8"
services:
    jenkins:
        build: .
        privileged: true
        user: root
        ports:
            - "8000:22"
            - 8086:8080
            - 50000:50000
        container_name: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        entrypoint: sh /root/entrypoint.sh