version: "3.8"
services:
    jenkins:
        #image: gsuscastelsc/jenkins:0.0.6
        build: .
        privileged: true
        user: root
        ports:
            - 8084:8080
            - 50000:50000
        container_name: jenkinsSB
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
        command: "tail -f /dev/null"